### ISSUE TITLE
[어드민] 쿠폰 및 이벤트 > 새 쿠폰 생성하기

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_QA#24]
[테스트 환경]
PC>맥

[현재 문제점]
1. 새 쿠폰생성하기 페이지에서 뒤로가기 버튼 클릭 시 '가게정보' 페이지로 이동함
<img width="211" alt="스크린샷 2024-06-23 오후 1 38 02" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/0b96ad9b-a551-4e70-82fe-f3ddafe1a22f">

2. 쿠폰미리보기 영역 block 으로 들어가있음
3. 쿠폰미리보기 > COUPON 텍스트 폰트
<img width="135" alt="스크린샷 2024-06-23 오후 1 41 36" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/96cb71c6-59c1-40f2-93ee-3901627c2f4f">

4. 필수항목 미입력시에도 '쿠폰 발행하기' 버튼 활성화 되어있음
5. 쿠폰 발행하기 완료 시 '가게정보'페이지로 이동함

[개선사항]
1.  뒤로가기 버튼 클릭 시 이전페이지(쿠폰 및 이벤트)로 이동 필요
2. 쿠폰미리보기 width값 372px로 고정 필요
3. 쿠폰미리보기 > COUPON 텍스트 폰트 Pretendard - Bold 로 적용 필요
<img width="172" alt="스크린샷 2024-06-23 오후 1 42 03" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/c6e1ee1a-9074-49e8-9792-22e2425963c4">

4. 필수항목 미입력시 '쿠폰 발행하기' 버튼 비활성화 필요
5. 쿠폰 발행하기 완료 시 '쿠폰 및 이벤트'로 이동 필요

**Comment by Dumbs-app** [comment]
6. 쿠폰 수량 입력시 숫자만 입력 가능하게 + 0으로 시작 못하도록 적용도 필요할 것 같습니다!
<img width="246" alt="스크린샷 2024-06-23 오후 1 55 56" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/c7cf0a51-0cb2-4337-b6ca-c5699bb28139">
<img width="226" alt="스크린샷 2024-06-23 오후 1 55 08" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/c7ca9a14-dfbe-477d-bfa2-c480e7bb8b0f">
<img width="212" alt="스크린샷 2024-06-23 오후 1 55 41" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/f1275d5b-3192-4509-8f76-20b03b82199b">
<img width="137" alt="스크린샷 2024-06-23 오후 1 53 31" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/2ecfbc93-ebb2-4f3c-a262-3ff412848e23">

**Comment by hateyoon** [comment]
5개 활성화만 되게 확인완료입니다!
