### ISSUE TITLE
[어드민] 우리가게 입점하기 > 로고 클릭시 랜딩 이슈

### ISSUE THREAD

**Issue by Dumbs-app** [Dumbs-app/Dumbs_QA#31]
[테스트 환경]
https://admin.dumbs.app/join
맥

[현재 문제점 & 개선사항]
**1. 우리가게 입점하기에서 DUMBS 로고 클릭 시** 
가게정보 입력하기 페이지로 이동됨
-> 로고 클릭시 어드민 홈 (https://admin.dumbs.app/login) 으로 이동해야함

<img width="334" alt="스크린샷 2024-07-02 오후 8 12 19" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/6f1fb9d5-c38e-4925-9f00-f73932ff088e">

**2. 우리가게 입점하기 > 삼선메뉴 > DUMBS 로고 클릭 시 액션 없음**
-> 로고 클릭 시 어드민 홈 (https://admin.dumbs.app/login) 으로 이동해야함
<img width="139" alt="스크린샷 2024-07-02 오후 8 11 22" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/fafaace6-52cc-4bab-b46a-7a30a571e9ef">

**Comment by Dumbs-app** [comment]
@heyman333 
영수님 1번은 반영 확인했는데요~!
2번 내용처럼 삼선메뉴에서 로고 클릭시에도 어드민 홈으로 이동하게 반영 가능하실까요?!

<img width="308" alt="스크린샷 2024-07-03 오후 9 39 26" src="https://github.com/Dumbs-app/MVP_QA/assets/160495249/43fa6c9d-ea00-4ed2-9123-1fcb33520aa9">

**Comment by heyman333** [comment]
@Dumbs-app 아 넵넵
